# CycloneDX SBOM Generation Configuration
# Generates Software Bill of Materials compliant with CycloneDX 1.5
# Implements: NIST SSDF PO.3.1, SLSA provenance requirements

# GitHub Actions workflow for SBOM generation
name: Generate SBOM

on:
  push:
    branches: [main, develop]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  generate-sbom:
    name: Generate and Sign SBOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Generate CycloneDX SBOM
      - name: Generate CycloneDX SBOM
        uses: CycloneDX/gh-node-module-generatebom@v1
        with:
          output: "./sbom-cyclonedx.json"

      # Generate SPDX SBOM
      - name: Generate SPDX SBOM
        run: |
          npm install -g @cyclonedx/cyclonedx-npm
          cyclonedx-npm --output-format spdx --output-file sbom-spdx.json

      # Validate SBOM
      - name: Validate CycloneDX SBOM
        run: |
          npm install -g @cyclonedx/cyclonedx-cli
          cyclonedx validate --input-file sbom-cyclonedx.json --input-format json

      # Install Cosign for signing
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      # Sign SBOM with Cosign (keyless)
      - name: Sign SBOM
        run: |
          cosign sign-blob --yes \
            --bundle sbom-cyclonedx.bundle \
            sbom-cyclonedx.json

          cosign sign-blob --yes \
            --bundle sbom-spdx.bundle \
            sbom-spdx.json

      # Verify signature
      - name: Verify Signature
        run: |
          cosign verify-blob \
            --bundle sbom-cyclonedx.bundle \
            --certificate-identity-regexp=".*" \
            --certificate-oidc-issuer-regexp=".*" \
            sbom-cyclonedx.json

      # Compare with previous SBOM
      - name: SBOM Diff Analysis
        if: github.event_name == 'push'
        run: |
          # Download previous SBOM
          gh api repos/${{ github.repository }}/releases/latest \
            --jq '.assets[] | select(.name=="sbom-cyclonedx.json") | .browser_download_url' \
            | xargs curl -L -o sbom-previous.json || echo "No previous SBOM"

          # Compare SBOMs
          if [ -f sbom-previous.json ]; then
            npm install -g @cyclonedx/cyclonedx-cli
            cyclonedx diff sbom-previous.json sbom-cyclonedx.json > sbom-diff.txt
            cat sbom-diff.txt
          fi

      # Upload SBOMs as artifacts
      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sboms
          path: |
            sbom-cyclonedx.json
            sbom-spdx.json
            *.bundle
            sbom-diff.txt

      # Attach SBOM to release
      - name: Attach SBOM to Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} \
            sbom-cyclonedx.json \
            sbom-spdx.json \
            sbom-cyclonedx.bundle \
            sbom-spdx.bundle

---
# CycloneDX Configuration File (cyclonedx.json)
# Place in repository root

{
  "version": "1.5",
  "serialNumber": "urn:uuid:{{ GENERATED_UUID }}",
  "metadata":
    {
      "timestamp": "{{ TIMESTAMP }}",
      "tools":
        [
          {
            "vendor": "CycloneDX",
            "name": "cyclonedx-node-module",
            "version": "latest",
          },
        ],
      "component":
        {
          "type": "application",
          "bom-ref": "{{ PROJECT_NAME }}",
          "name": "{{ PROJECT_NAME }}",
          "version": "{{ VERSION }}",
          "description": "{{ DESCRIPTION }}",
          "licenses": [{ "license": { "id": "{{ LICENSE }}" } }],
        },
    },
  "components": [],
  "dependencies": [],
  "vulnerabilities": [],
}
---
# Validation Commands
#
# Generate SBOM locally:
#   npm install -g @cyclonedx/cyclonedx-npm
#   cyclonedx-npm --output-file sbom.json
#
# Validate SBOM:
#   cyclonedx validate --input-file sbom.json
#
# Sign SBOM:
#   cosign sign-blob --yes --bundle sbom.bundle sbom.json
#
# Verify signature:
#   cosign verify-blob --bundle sbom.bundle --certificate-identity-regexp=".*" \
#     --certificate-oidc-issuer-regexp=".*" sbom.json
#
# Compare SBOMs:
#   cyclonedx diff sbom-old.json sbom-new.json
#
# Query SBOM:
#   jq '.components[] | select(.type=="library") | .name' sbom.json
