"""Build the Jupyter Book documentation to verify GitHub Pages integration (#53)."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

# Skip automatically if jupyter-book is not installed in the environment running pytest.
pytest.importorskip(
    "jupyter_book",
    reason="jupyter-book is required to build documentation",
)


@pytest.mark.slow
def test_jupyter_book_builds_successfully(tmp_path: Path) -> None:
    """Ensure the docs build cleanly using the same command as the Pages workflow."""
    output_dir = tmp_path / "book-build"
    command = ["jb", "build", "docs", "--path-output", str(output_dir)]

    subprocess.run(command, check=True)

    index_html = output_dir / "_build" / "html" / "index.html"
    assert (
        index_html.exists()
    ), f"Expected {index_html} to be generated by jupyter-book build."
