name: Accessibility Checks
on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1' # Weekly on Monday at 6am

jobs:
  # axe-core accessibility testing
  axe-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Start app
        run: |
          npm start &
          npx wait-on http://localhost:3000

      - name: Run axe accessibility tests
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:3000 --exit

      - name: Run axe with Playwright
        run: |
          npm install -D @axe-core/playwright
          npx playwright test tests/accessibility/

  # pa11y accessibility testing
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and start app
        run: |
          npm run build
          npm start &
          npx wait-on http://localhost:3000

      - name: Run pa11y
        run: |
          npm install -g pa11y pa11y-ci
          pa11y-ci --config .pa11yci.json

  # Lighthouse accessibility audit
  lighthouse-a11y:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Run Lighthouse accessibility audit
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            http://localhost:3000
          configPath: ./lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Check accessibility score
        run: |
          # Extract accessibility score from Lighthouse results
          # Fail if score < 90
          echo "Checking accessibility score >= 90"

  # WAVE accessibility checker
  wave:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and start app
        run: |
          npm run build
          npm start &
          npx wait-on http://localhost:3000

      - name: Run WAVE API check
        env:
          WAVE_API_KEY: {% raw %}${{ secrets.WAVE_API_KEY }}{% endraw %}
        run: |
          # Use WAVE API to check accessibility
          curl "https://wave.webaim.org/api/request?key=${WAVE_API_KEY}&url=http://localhost:3000"

  # HTML validation
  html-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Validate HTML
        run: |
          npm install -g html-validate
          html-validate "dist/**/*.html"

  # Color contrast checker
  contrast-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check color contrast
        run: |
          npm install -g color-contrast-checker
          # Check all CSS files for WCAG AA/AAA compliance
          find src -name "*.css" -exec color-contrast-checker {} \;

  # Keyboard navigation testing
  keyboard-nav:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run keyboard navigation tests
        run: npx playwright test tests/accessibility/keyboard-nav.spec.ts

  # Screen reader compatibility
  screen-reader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test ARIA labels and roles
        run: |
          # Run tests to verify ARIA attributes
          npm run test:a11y

      - name: Generate accessibility report
        uses: actions/upload-artifact@v4
        with:
          name: accessibility-report
          path: accessibility-report/
