name: Sign and Attest Artifacts
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  sign-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Download release assets
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
        run: |
          gh release download {% raw %}${{ github.event.release.tag_name }}{% endraw %} -D ./artifacts || true

      - name: Sign artifacts with Cosign
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          for file in ./artifacts/*; do
            if [ -f "$file" ]; then
              echo "Signing $file"
              cosign sign-blob --yes "$file" --bundle "${file}.cosign.bundle"
            fi
          done

      - name: Upload signed bundles
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
        run: |
          for bundle in ./artifacts/*.cosign.bundle; do
            if [ -f "$bundle" ]; then
              gh release upload {% raw %}${{ github.event.release.tag_name }}{% endraw %} "$bundle" --clobber
            fi
          done

  slsa-provenance:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Generate SLSA provenance
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
        with:
          base64-subjects: {% raw %}${{ steps.hash.outputs.hashes }}{% endraw %}
          upload-assets: true

      - name: Compute artifact hashes
        id: hash
        run: |
          cd ./artifacts
          sha256sum * > checksums.txt
          cat checksums.txt
          echo "hashes=$(base64 -w0 < checksums.txt)" >> $GITHUB_OUTPUT
